# Site settings
title: Navi+ Help Center
site_name: "Help" # Display name next to logo in navbar
lang: en
email: support@naviplus.io
description: "Navi+ Help Center — Official guides, tutorials and FAQs for Mega Menu, Tab Bar, Slide Menu, Sticky Navbar, FAB and Grid Menu on Shopify, WordPress, Wix and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://help.naviplus.io"
social_image: "/assets/images/naviplus-social-share.jpg"
twitter_username: "@NaviPlusOfficial"
copyright_text: "© 2026 by Navi+"
copyright_url: "https://naviplus.io"
encoding: UTF-8

# Server settings
port: 4004

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# Build settings
markdown: kramdown

# Jekyll Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/
    index: true
